# roster.py — curated layer of the HumanityCards data pipeline.
#
# One entry per humanId from the on-chain roster (humanity-cards-roster.md).
# Fields per tuple:
#   (humanId, rosterName, wikiTitle, category, role, bio, born, died, dom, intl)
#
#   rosterName : exact name as it appears on-chain / in roster.md (data.js key)
#   wikiTitle  : English Wikipedia article title (redirects are followed)
#   category   : drives the dominion/intellect base scores (see build_data.py)
#   role       : short epithet shown on the card
#   bio        : one-sentence, fact-checked biography
#   born/died  : fallback years (negative = BCE), used when Wikidata has no
#                year-precision date. died=None means living (or vanished).
#   dom/intl   : per-figure overrides of the category base (None = use base).
#
# Notes on oddities preserved from the 2018 contract:
#   - humanId 66 and 191 are BOTH Sigmund Freud (the contract listed him twice)
#   - humanId 164 "Ramesses II" and 212 "Ramesses the Great" are the same king
#   - several names are contract-spellings ("Gengis Khan", "Kim Jung Un",
#     "Goazu of Han", "Ben Laden", "Isebella I of Castile", ...) — we keep the
#     on-chain spelling as the display name and map to the right article.

ROSTER = [
    (0, "Moses", "Moses", "prophet", "Hebrew prophet and lawgiver",
     "Biblical leader who, by tradition, led the Israelites out of Egypt and received the Law at Sinai.",
     -1391, -1271, 70, 75),
    (1, "Confucius", "Confucius", "philosopher", "Chinese philosopher",
     "Teacher whose ethics of family, ritual and good governance shaped East Asian civilisation for two millennia.",
     -551, -479, 75, 92),
    (2, "Einstein", "Albert Einstein", "scientist", "Theoretical physicist",
     "Reinvented physics with special and general relativity; the 1921 Nobel Prize came for the photoelectric effect.",
     1879, 1955, 45, 100),
    (3, "Paul the Apostle", "Paul the Apostle", "religious", "Apostle of Christianity",
     "Pharisee-turned-missionary whose journeys and epistles carried Christianity across the Roman world.",
     5, 64, 70, 80),
    (4, "Christopher Columbus", "Christopher Columbus", "explorer", "Genoese explorer",
     "His four Atlantic crossings for Spain opened the Americas to lasting European contact and conquest.",
     1451, 1506, 70, None),
    (5, "Jesus", "Jesus", "founder", "Central figure of Christianity",
     "Galilean preacher crucified under Pontius Pilate; the faith founded in his name became the world's largest.",
     -4, 30, 90, 88),
    (6, "Galileo", "Galileo Galilei", "scientist", "Father of observational astronomy",
     "Turned the telescope on the heavens, championed Copernicus, and was tried by the Inquisition for it.",
     1564, 1642, None, 97),
    (7, "Gutenberg", "Johannes Gutenberg", "inventor", "Printing pioneer",
     "His movable-type press, perfected by about 1450 in Mainz, made books cheap and ideas unstoppable.",
     1400, 1468, None, 88),
    (8, "Lavoisier", "Antoine Lavoisier", "scientist", "Father of modern chemistry",
     "Named oxygen, established conservation of mass, and died on the guillotine during the Terror.",
     1743, 1794, None, 95),
    (9, "Constantin", "Constantine the Great", "emperor", "First Christian Roman emperor",
     "Won the empire at the Milvian Bridge, legalised Christianity, and founded Constantinople.",
     272, 337, 85, None),
    (10, "James Watt", "James Watt", "inventor", "Steam-engine improver",
     "His separate-condenser steam engine powered the Industrial Revolution; the watt is named for him.",
     1736, 1819, None, 90),
    (11, "Faraday", "Michael Faraday", "scientist", "Experimental physicist",
     "Self-taught master of electromagnetism whose discovery of induction made electric power possible.",
     1791, 1867, None, 94),
    (12, "Maxwell", "James Clerk Maxwell", "scientist", "Mathematical physicist",
     "His equations unified electricity, magnetism and light — the bridge from Newton to Einstein.",
     1831, 1879, None, 98),
    (13, "Muhammad", "Muhammad", "founder", "Prophet of Islam",
     "United Arabia under Islam and the Quran; within a century his followers ruled from Spain to Persia.",
     570, 632, 95, 85),
    (14, "Buddha", "Gautama Buddha", "founder", "Founder of Buddhism",
     "Prince-turned-ascetic whose path out of suffering spread from India across all of Asia.",
     -563, -483, 85, 90),
    (15, "Cai Lun", "Cai Lun", "inventor", "Inventor of paper",
     "Han court official credited with perfecting papermaking around 105 CE — one of history's great inventions.",
     50, 121, 50, 85),
    (16, "Aristotle", "Aristotle", "philosopher", "Greek polymath",
     "Pupil of Plato and tutor of Alexander; systematised logic, biology, ethics and politics for 2,000 years.",
     -384, -322, None, 99),
    (17, "Euclid", "Euclid", "mathematician", "Father of geometry",
     "His Elements organised mathematics so well it stayed the standard textbook into the 19th century.",
     -325, -265, None, 96),
    (18, "Newton", "Isaac Newton", "scientist", "Physicist and mathematician",
     "Laws of motion, universal gravitation and the calculus — the foundation of classical science.",
     1643, 1727, 45, 100),
    (19, "Darwin", "Charles Darwin", "scientist", "Naturalist",
     "On the Origin of Species (1859) made evolution by natural selection the unifying idea of biology.",
     1809, 1882, None, 97),
    (20, "Qin Shi Huang", "Qin Shi Huang", "emperor", "First Emperor of China",
     "Unified the warring states, standardised script and measures, began the Great Wall — and was buried with the Terracotta Army.",
     -259, -210, 88, None),
    (21, "Augustus", "Augustus", "emperor", "First Roman emperor",
     "Caesar's heir who ended the civil wars at Actium and ruled a peaceful Rome for four decades.",
     -63, 14, 93, 82),
    (22, "Leonidas", "Leonidas I", "general", "Spartan king",
     "Led the 300 at Thermopylae in 480 BCE, dying in a stand that became the legend of sacrifice.",
     -540, -480, 45, None),
    (23, "Martin Luther", "Martin Luther", "religious", "Protestant reformer",
     "His Ninety-five Theses of 1517 split Western Christianity and put the Bible in the people's language.",
     1483, 1546, 70, None),
    (24, "Washington", "George Washington", "leader", "First U.S. president",
     "Commanded the Continental Army to victory, then set the precedent by handing power back.",
     1732, 1799, 80, 75),
    (25, "Karl Marx", "Karl Marx", "philosopher", "Revolutionary philosopher",
     "Author of Capital and the Communist Manifesto; his critique of capitalism reshaped the 20th century.",
     1818, 1883, 55, 94),
    (26, "Goazu of Han", "Emperor Gaozu of Han", "emperor", "Founder of the Han dynasty",
     "Peasant rebel Liu Bang, who outlasted the Qin collapse and founded China's defining dynasty.",
     -256, -195, 80, None),
    (27, "Gengis Khan", "Genghis Khan", "conqueror", "Mongol conqueror",
     "Temüjin united the steppe tribes and built the largest contiguous land empire in history.",
     1162, 1227, 100, None),
    (28, "Adam Smith", "Adam Smith", "economist", "Father of economics",
     "The Wealth of Nations (1776) described markets and the division of labour — modern economics begins here.",
     1723, 1790, None, 94),
    (29, "Shakespeare", "William Shakespeare", "writer", "English playwright",
     "Some 37 plays and 154 sonnets that remade the English language and the human stage.",
     1564, 1616, None, 96),
    (30, "John Dalton", "John Dalton", "scientist", "Chemist",
     "His atomic theory gave chemistry its foundation: matter as atoms combining in fixed ratios.",
     1766, 1844, None, 88),
    (31, "Alexander The Great", "Alexander the Great", "conqueror", "Macedonian conqueror",
     "Undefeated from Greece to India by age 30, spreading Hellenism across three continents.",
     -356, -323, 97, 85),
    (32, "Napoleon", "Napoleon", "conqueror", "Emperor of the French",
     "Revolutionary general who crowned himself emperor, redrew Europe and codified its laws — until Waterloo.",
     1769, 1821, 95, 88),
    (33, "Thomas Edison", "Thomas Edison", "inventor", "American inventor",
     "Phonograph, practical light bulb and the industrial research lab — 1,093 U.S. patents.",
     1847, 1931, None, 88),
    (34, "Mansa Musa", "Mansa Musa", "monarch", "Emperor of Mali",
     "His gold-laden 1324 pilgrimage to Mecca was so lavish it reportedly depressed prices in Cairo for years.",
     1280, 1337, 75, None),
    (35, "Morton", "William T. G. Morton", "physician", "Anaesthesia pioneer",
     "Boston dentist who gave the first successful public demonstration of ether surgery in 1846.",
     1819, 1868, 30, 70),
    (36, "Marconi", "Guglielmo Marconi", "inventor", "Radio pioneer",
     "Sent the first transatlantic wireless signal in 1901; shared the 1909 Nobel Prize in Physics.",
     1874, 1937, None, 80),
    (37, "Hitler", "Adolf Hitler", "dictator", "Nazi dictator",
     "Led Germany into World War II and ordered the Holocaust — tens of millions died in the war he started.",
     1889, 1945, 92, None),
    (38, "Plato", "Plato", "philosopher", "Greek philosopher",
     "Student of Socrates and founder of the Academy; Western philosophy has been called footnotes to him.",
     -428, -348, None, 98),
    (39, "Malcolm X", "Malcolm X", "activist", "Civil-rights leader",
     "Nation of Islam minister turned independent voice for Black empowerment; assassinated in 1965.",
     1925, 1965, 45, None),
    (40, "Bell", "Alexander Graham Bell", "inventor", "Inventor of the telephone",
     "Patented the telephone in 1876 and co-founded the company that became AT&T.",
     1847, 1922, None, 85),
    (41, "Fleming", "Alexander Fleming", "scientist", "Discoverer of penicillin",
     "His contaminated petri dish in 1928 began the antibiotic age; Nobel laureate, 1945.",
     1881, 1955, None, 84),
    (42, "Socrates", "Socrates", "philosopher", "Greek philosopher",
     "Questioned Athens into philosophy itself; condemned to drink hemlock for corrupting the youth.",
     -470, -399, None, 96),
    (43, "Beethoven", "Ludwig van Beethoven", "composer", "German composer",
     "Bridged the Classical and Romantic eras and wrote the Ninth Symphony almost completely deaf.",
     1770, 1827, None, 94),
    (44, "Heisenberg", "Werner Heisenberg", "scientist", "Quantum physicist",
     "Formulated matrix quantum mechanics and the uncertainty principle in his twenties; Nobel laureate, 1932.",
     1901, 1976, None, 96),
    (45, "David", "David", "monarch", "King of Israel",
     "Shepherd, giant-slayer and psalmist who, in the biblical account, united Israel and made Jerusalem its capital.",
     -1040, -970, 55, None),
    (46, "Simon Bolivar", "Simón Bolívar", "revolutionary", "The Liberator",
     "Freed six South American nations from Spanish rule; Bolivia bears his name.",
     1783, 1830, 75, None),
    (47, "Descartes", "René Descartes", "philosopher", "Father of modern philosophy",
     "\"I think, therefore I am\" — plus the coordinate geometry that bears his name.",
     1596, 1650, None, 97),
    (48, "Michelangelo", "Michelangelo", "artist", "Renaissance master",
     "David, the Pietà and the Sistine ceiling — sculptor, painter and architect of genius.",
     1475, 1564, None, 94),
    (49, "Urban II", "Pope Urban II", "religious", "Crusading pope",
     "His 1095 sermon at Clermont — \"Deus vult\" — launched the First Crusade.",
     1035, 1099, 70, None),
    (50, "Omar ibn al-Khattab", "Umar", "emperor", "Second caliph",
     "Under his caliphate Islam took Persia, Syria, Egypt and Jerusalem within a single decade.",
     584, 644, 88, 75),
    (51, "Ashoka", "Ashoka", "emperor", "Mauryan emperor",
     "After the bloodbath at Kalinga he embraced Buddhism and carved edicts of nonviolence across India.",
     -304, -232, 82, None),
    (52, "Augustine of Hippo", "Augustine of Hippo", "religious", "Christian theologian",
     "Confessions and The City of God set the course of Western theology for a millennium.",
     354, 430, None, 92),
    (53, "Harvey", "William Harvey", "physician", "Physician",
     "First to demonstrate that blood circulates, driven by the heart — the start of modern physiology.",
     1578, 1657, None, 86),
    (54, "Rutherford", "Ernest Rutherford", "scientist", "Father of nuclear physics",
     "Discovered the atomic nucleus and the proton, and was first to split the atom.",
     1871, 1937, None, 94),
    (55, "John Calvin", "John Calvin", "religious", "Protestant reformer",
     "From Geneva, his doctrine of predestination shaped Reformed churches worldwide.",
     1509, 1564, 60, None),
    (56, "Idi Amin", "Idi Amin", "dictator", "Ugandan dictator",
     "His 1971–79 rule killed an estimated 300,000 Ugandans and expelled the country's Asian minority.",
     1925, 2003, 42, None),
    (57, "Max Planck", "Max Planck", "scientist", "Father of quantum theory",
     "His 1900 quantum of action opened modern physics; Nobel laureate, 1918.",
     1858, 1947, None, 96),
    (58, "Pinochet", "Augusto Pinochet", "dictator", "Chilean dictator",
     "Seized power in the 1973 coup; his junta killed or disappeared thousands while remaking Chile's economy.",
     1915, 2006, 50, None),
    (59, "Nikolaus Otto", "Nicolaus Otto", "inventor", "Engine inventor",
     "His 1876 four-stroke internal-combustion engine still powers most of the world's cars.",
     1832, 1891, None, 78),
    (60, "Pizarro", "Francisco Pizarro", "explorer", "Conquistador",
     "With under 200 men he captured Atahualpa and brought down the Inca Empire.",
     1478, 1541, 68, None),
    (61, "Cortes", "Hernán Cortés", "explorer", "Conquistador",
     "Landed in Mexico in 1519; within two years the Aztec Empire was Spain's.",
     1485, 1547, 70, None),
    (62, "Jefferson", "Thomas Jefferson", "leader", "Third U.S. president",
     "Principal author of the Declaration of Independence; doubled the U.S. with the Louisiana Purchase.",
     1743, 1826, 80, 90),
    (63, "Isebella I of Castile", "Isabella I of Castile", "monarch", "Queen of Castile",
     "United Spain with Ferdinand, completed the Reconquista, and bankrolled Columbus — and the Inquisition.",
     1451, 1504, 70, None),
    (64, "Stalin", "Joseph Stalin", "dictator", "Soviet dictator",
     "Industrialised the USSR and won the Eastern Front, at the cost of millions dead in purges and famines.",
     1878, 1953, 95, None),
    (65, "William the Conqueror", "William the Conqueror", "monarch", "Norman king of England",
     "Won England at Hastings in 1066, rewiring its language, law and landholding.",
     1028, 1087, 75, None),
    (66, "Freud", "Sigmund Freud", "physician", "Father of psychoanalysis",
     "Mapped the unconscious — id, ego, superego — and made talking itself a therapy.",
     1856, 1939, 40, 92),
    (67, "Edward Jenner", "Edward Jenner", "physician", "Vaccination pioneer",
     "His 1796 cowpox experiment created the smallpox vaccine; the disease has since been eradicated.",
     1749, 1823, None, 86),
    (68, "Rontgen", "Wilhelm Röntgen", "scientist", "Discoverer of X-rays",
     "Found X-rays in 1895 and won the first Nobel Prize in Physics; he refused to patent them.",
     1845, 1923, None, 88),
    (69, "Bach", "Johann Sebastian Bach", "composer", "Baroque composer",
     "Cantor of Leipzig whose fugues and cantatas remain the deepest foundation of Western music.",
     1685, 1750, None, 94),
    (70, "Lao Tseu", "Laozi", "philosopher", "Daoist sage",
     "Semi-legendary author of the Tao Te Ching, the classic of effortless action.",
     -571, -471, 50, 88),
    (71, "Voltaire", "Voltaire", "philosopher", "Enlightenment wit",
     "Pamphleteer of tolerance and reason who feuded with kings and the Church alike.",
     1694, 1778, None, 92),
    (72, "Kepler", "Johannes Kepler", "scientist", "Astronomer",
     "His three laws of planetary motion turned Copernicus's idea into precise science.",
     1571, 1630, None, 95),
    (73, "Chiang Kai Shek", "Chiang Kai-shek", "leader", "Chinese Nationalist leader",
     "Ruled China through the war with Japan, lost the civil war to Mao, and rebuilt on Taiwan.",
     1887, 1975, 60, None),
    (74, "Euler", "Leonhard Euler", "mathematician", "Swiss mathematician",
     "The most prolific mathematician ever — e, i, π, graph theory, and hundreds of papers written blind.",
     1707, 1783, None, 99),
    (75, "Jean-Jacques Rousseau", "Jean-Jacques Rousseau", "philosopher", "Enlightenment philosopher",
     "The Social Contract's \"general will\" inspired both modern democracy and the French Revolution.",
     1712, 1778, None, 90),
    (76, "Machiavelli", "Niccolò Machiavelli", "philosopher", "Political theorist",
     "The Prince told rulers how power actually works; his name became an adjective.",
     1469, 1527, 35, 90),
    (77, "Malthus", "Thomas Robert Malthus", "economist", "Political economist",
     "Argued population outruns food supply; his essay sparked Darwin's key insight.",
     1766, 1834, None, 85),
    (78, "Kennedy", "John F. Kennedy", "leader", "35th U.S. president",
     "Faced down the Cuban Missile Crisis and launched the Moon race; assassinated in Dallas, 1963.",
     1917, 1963, 88, None),
    (79, "Hideki Tojo", "Hideki Tojo", "general", "Japanese war leader",
     "Prime minister who ordered the attack on Pearl Harbor; hanged as a war criminal in 1948.",
     1884, 1948, 70, None),
    (80, "Mani", "Mani (prophet)", "prophet", "Founder of Manichaeism",
     "His syncretic religion of light and darkness once stretched from Rome to China.",
     216, 274, 55, None),
    (81, "Lenin", "Vladimir Lenin", "revolutionary", "Bolshevik revolutionary",
     "Led the October Revolution of 1917 and founded the Soviet state.",
     1870, 1924, 88, 85),
    (82, "Sui Wendi", "Emperor Wen of Sui", "emperor", "Founder of the Sui dynasty",
     "Reunified China after three centuries of division and laid the ground for the Grand Canal.",
     541, 604, 78, None),
    (83, "Vasco da Gama", "Vasco da Gama", "explorer", "Portuguese explorer",
     "First to sail from Europe to India, in 1498, opening the ocean route to Asia.",
     1460, 1524, None, None),
    (84, "Cyrus The Great", "Cyrus the Great", "emperor", "Founder of the Persian Empire",
     "Built the largest empire the world had yet seen and freed the exiles of Babylon.",
     -600, -530, 90, None),
    (85, "Peter The Great", "Peter the Great", "monarch", "Russian tsar",
     "Dragged Russia toward Europe, built a navy, and raised a new capital at St Petersburg.",
     1672, 1725, 84, None),
    (86, "Mao Zedong", "Mao Zedong", "dictator", "Chinese communist leader",
     "Won the civil war and founded the PRC; the Great Leap and Cultural Revolution killed tens of millions.",
     1893, 1976, 95, 75),
    (87, "Francis Bacon", "Francis Bacon", "philosopher", "Father of empiricism",
     "Lord Chancellor who codified the experimental method that science still runs on.",
     1561, 1626, None, 92),
    (88, "Henry Ford", "Henry Ford", "business", "Automaker",
     "The Model T and the moving assembly line put the world on wheels.",
     1863, 1947, 65, 82),
    (89, "Mencius", "Mencius", "philosopher", "Confucian sage",
     "The \"second sage\" of Confucianism, who argued that human nature is innately good.",
     -372, -289, 45, 88),
    (90, "Zoroastre", "Zoroaster", "prophet", "Persian prophet",
     "Founder of Zoroastrianism, the ancient Persian faith of truth against the lie.",
     -628, -551, 60, None),
    (91, "Elizabeth I", "Elizabeth I", "monarch", "Queen of England",
     "The Virgin Queen saw off the Spanish Armada and presided over Shakespeare's England.",
     1533, 1603, 72, None),
    (92, "Gorbatchev", "Mikhail Gorbachev", "leader", "Last Soviet leader",
     "Glasnost and perestroika ended the Cold War — and, unintentionally, the USSR itself.",
     1931, 2022, 85, None),
    (93, "Menes", "Menes", "pharaoh", "First pharaoh",
     "Traditional unifier of Upper and Lower Egypt and founder of the First Dynasty.",
     -3150, -3100, 55, None),
    (94, "Charlemagne", "Charlemagne", "emperor", "Emperor of the West",
     "King of the Franks crowned emperor in 800, uniting most of Western Europe for the first time since Rome.",
     748, 814, 86, None),
    (95, "Homer", "Homer", "writer", "Greek epic poet",
     "Traditional singer of the Iliad and the Odyssey, the fountainhead of Western literature.",
     -800, -701, None, 88),
    (96, "Justinian", "Justinian I", "emperor", "Byzantine emperor",
     "Reconquered the West, built Hagia Sophia, and codified Roman law in the Corpus Juris Civilis.",
     482, 565, 80, None),
    (97, "Mahavira", "Mahavira", "founder", "Founder of Jainism",
     "The 24th tirthankara, whose radical doctrine of nonviolence still guides millions of Jains.",
     -599, -527, 50, 80),
    (98, "Trump", "Donald Trump", "leader", "45th & 47th U.S. president",
     "Real-estate showman turned president — twice impeached, twice elected.",
     1946, None, 90, None),
    (99, "Xi Jinping", "Xi Jinping", "leader", "Chinese paramount leader",
     "Abolished term limits and centralised power to a degree unseen since Mao.",
     1953, None, 92, None),
    (100, "Macron", "Emmanuel Macron", "leader", "French president",
     "Youngest French head of state since Napoleon, elected at 39 in 2017.",
     1977, None, 62, None),
    (101, "Kim Jung Un", "Kim Jong Un", "dictator", "North Korean leader",
     "Third Kim to rule the DPRK — nuclear arsenal, total control.",
     1984, None, 45, None),
    (102, "Merkel", "Angela Merkel", "leader", "German chancellor",
     "Quantum chemist who led Germany — and often Europe — for sixteen years.",
     1954, None, 70, 85),
    (103, "Obama", "Barack Obama", "leader", "44th U.S. president",
     "First Black U.S. president; healthcare reform at home, the bin Laden raid abroad.",
     1961, None, 90, None),
    (104, "Mussolini", "Benito Mussolini", "dictator", "Fascist dictator",
     "Invented fascism, ruled Italy for two decades, and was shot by partisans in 1945.",
     1883, 1945, 72, None),
    (105, "Pol Pot", "Pol Pot", "dictator", "Khmer Rouge leader",
     "His \"Year Zero\" killed roughly a quarter of Cambodia's population in under four years.",
     1925, 1998, 40, None),
    (106, "Chavez", "Hugo Chávez", "leader", "Venezuelan president",
     "Paratrooper whose \"Bolivarian revolution\" transformed and polarised Venezuela.",
     1954, 2013, 50, None),
    (107, "Mandela", "Nelson Mandela", "leader", "South African president",
     "Twenty-seven years in prison, then led South Africa out of apartheid as its first Black president.",
     1918, 2013, 60, 80),
    (108, "Gaddafi", "Muammar Gaddafi", "dictator", "Libyan strongman",
     "Ruled Libya for 42 years on oil wealth and eccentric terror; killed in the 2011 uprising.",
     1942, 2011, 50, None),
    (109, "Zuckerberg", "Mark Zuckerberg", "tech", "Facebook founder",
     "Built Facebook from a dorm room into a platform used by some three billion people.",
     1984, None, 75, None),
    (110, "Jeff Bezos", "Jeff Bezos", "tech", "Amazon founder",
     "Turned an online bookstore into the everything store — and then went to space.",
     1964, None, 72, None),
    (111, "Steve Jobs", "Steve Jobs", "tech", "Apple co-founder",
     "Mac, iPod, iPhone — fused computing with design and changed daily life.",
     1955, 2011, 70, 85),
    (112, "Bill Gates", "Bill Gates", "tech", "Microsoft co-founder",
     "Put a computer on every desk, then turned his fortune to global health.",
     1955, None, 75, 90),
    (113, "Joan of Arc", "Joan of Arc", "general", "French heroine",
     "Teenage visionary who lifted the siege of Orléans; burned at 19, later canonised a saint.",
     1412, 1431, 45, None),
    (114, "Marie Antoinette", "Marie Antoinette", "monarch", "Queen of France",
     "Austrian-born queen guillotined by the Revolution; \"let them eat cake\" was never hers.",
     1755, 1793, 50, None),
    (115, "Caesar", "Julius Caesar", "general", "Roman dictator",
     "Conquered Gaul, crossed the Rubicon, and was stabbed in the Senate on the Ides of March.",
     -100, -44, 90, 85),
    (116, "Larry Page", "Larry Page", "tech", "Google co-founder",
     "Co-invented PageRank — the algorithm that organised the web.",
     1973, None, 72, 90),
    (117, "Sergey Brin", "Sergey Brin", "tech", "Google co-founder",
     "Soviet-born co-founder of Google and later head of its moonshot lab.",
     1973, None, 72, 90),
    (118, "Putin", "Vladimir Putin", "leader", "Russian president",
     "KGB officer turned longest-serving Kremlin leader since Stalin; invaded Ukraine in 2022.",
     1952, None, 85, None),
    (119, "Cleopatra", "Cleopatra", "monarch", "Last pharaoh of Egypt",
     "Allied with Caesar and Antony to keep Egypt independent; chose the asp over Octavian's triumph.",
     -69, -30, 65, 80),
    (120, "Mark Antony", "Mark Antony", "general", "Roman triumvir",
     "Caesar's lieutenant, who ruled the East with Cleopatra — and lost everything at Actium.",
     -83, -30, 70, None),
    (121, "Pompey", "Pompey", "general", "Pompey the Great",
     "Cleared the pirates and conquered the East, then lost the Republic to Caesar at Pharsalus.",
     -106, -48, 75, None),
    (122, "Crassus", "Marcus Licinius Crassus", "general", "Richest man in Rome",
     "Crushed Spartacus, bankrolled the First Triumvirate, and died chasing Parthian glory.",
     -115, -53, 65, None),
    (123, "Spartacus", "Spartacus", "revolutionary", "Gladiator rebel",
     "Thracian gladiator who led tens of thousands of escaped slaves against Rome for two years.",
     -103, -71, 40, None),
    (124, "Sulla", "Sulla", "general", "Roman dictator",
     "First to march his legions on Rome; his proscriptions wrote the playbook Caesar finished.",
     -138, -78, 72, None),
    (125, "Cicero", "Cicero", "statesman", "Roman orator",
     "Rome's greatest speaker and prose stylist; beheaded for opposing Antony.",
     -106, -43, None, 90),
    (126, "Charles de Gaulle", "Charles de Gaulle", "leader", "Leader of Free France",
     "Refused the 1940 surrender, led Free France from London, and founded the Fifth Republic.",
     1890, 1970, 78, None),
    (127, "Churchill", "Winston Churchill", "leader", "British war leader",
     "His defiance in 1940 carried Britain through its darkest hour; Nobel laureate in Literature.",
     1874, 1965, 85, 85),
    (128, "Hillary Clinton", "Hillary Clinton", "politician", "U.S. stateswoman",
     "First Lady, senator, Secretary of State, and first woman to win a major-party presidential nomination.",
     1947, None, 60, None),
    (129, "John Rockefeller", "John D. Rockefeller", "business", "Oil magnate",
     "Standard Oil made him history's richest private citizen — until antitrust law broke it apart.",
     1839, 1937, 70, None),
    (130, "Mugabe", "Robert Mugabe", "dictator", "Zimbabwean ruler",
     "Liberation hero turned 37-year autocrat who rode Zimbabwe into hyperinflation.",
     1924, 2019, 45, None),
    (131, "Kadyrov", "Ramzan Kadyrov", "politician", "Chechen strongman",
     "Rules Chechnya for the Kremlin with a personal army and a personality cult.",
     1976, None, 35, None),
    (132, "Mauricio Macri", "Mauricio Macri", "politician", "Argentine president",
     "Businessman president (2015–19) who tried to reopen Argentina to world markets.",
     1959, None, 40, None),
    (133, "Elizabeth II", "Elizabeth II", "monarch", "British queen",
     "Seventy years on the throne — the longest reign in British history, from Churchill to Truss.",
     1926, 2022, 80, None),
    (134, "Philippe of Belgium", "Philippe of Belgium", "monarch", "King of the Belgians",
     "Seventh king of the Belgians, on the throne since his father's abdication in 2013.",
     1960, None, 35, None),
    (135, "George W. Bush", "George W. Bush", "leader", "43rd U.S. president",
     "Answered the September 11 attacks with wars in Afghanistan and Iraq.",
     1946, None, 88, None),
    (136, "George Bush", "George H. W. Bush", "leader", "41st U.S. president",
     "CIA chief turned president who won the Gulf War and managed the Cold War's end.",
     1924, 2018, 88, None),
    (137, "Michel Temer", "Michel Temer", "politician", "Brazilian president",
     "Took office on Dilma Rousseff's impeachment in 2016.",
     1940, None, 40, None),
    (138, "Fidel Castro", "Fidel Castro", "dictator", "Cuban revolutionary",
     "Took Havana in 1959 and defied eleven U.S. presidents across half a century.",
     1926, 2016, 55, 75),
    (139, "Tsipras", "Alexis Tsipras", "politician", "Greek prime minister",
     "Led Syriza through the 2015 debt-crisis showdown with Europe.",
     1974, None, 38, None),
    (140, "Ali Khamenei", "Ali Khamenei", "leader", "Iran's Supreme Leader",
     "Has held Iran's highest office since 1989, outlasting a procession of U.S. presidents.",
     1939, None, 65, None),
    (141, "Saddam Hussein", "Saddam Hussein", "dictator", "Iraqi dictator",
     "Ruled Iraq by fear through three wars; hanged in 2006 after the U.S. invasion.",
     1937, 2006, 55, None),
    (142, "Netanyahu", "Benjamin Netanyahu", "leader", "Israeli prime minister",
     "Israel's longest-serving prime minister, in and out of power since 1996.",
     1949, None, 55, None),
    (143, "Mohammed VI", "Mohammed VI of Morocco", "monarch", "King of Morocco",
     "Alaouite king since 1999 and a cautious moderniser of Morocco.",
     1963, None, 45, None),
    (144, "Felipe VI", "Felipe VI", "monarch", "King of Spain",
     "Took the Spanish throne on his father's abdication in 2014.",
     1968, None, 42, None),
    (145, "Bashar al Assad", "Bashar al-Assad", "dictator", "Deposed Syrian president",
     "Ophthalmologist-turned-president whose civil war killed half a million; fled to Moscow when Damascus fell in 2024.",
     1965, None, 45, None),
    (146, "Erdogan", "Recep Tayyip Erdoğan", "leader", "Turkish president",
     "Has dominated Turkish politics since 2003, recasting the secular republic in his image.",
     1954, None, 65, None),
    (147, "Satoshi Nakamoto", "Satoshi Nakamoto", "mystery", "Bitcoin's creator",
     "Pseudonymous author of the 2008 white paper; mined the genesis block, then vanished.",
     1975, None, 60, 95),
    (148, "Attila", "Attila", "conqueror", "Scourge of God",
     "Hun king whose horsemen terrorised both halves of the Roman Empire.",
     406, 453, 88, None),
    (149, "Nero", "Nero", "emperor", "Roman emperor",
     "Matricide, showman and persecutor of Christians; Rome burned on his watch.",
     37, 68, 78, None),
    (150, "Hannibal", "Hannibal", "general", "Carthaginian general",
     "Crossed the Alps with elephants and crushed Rome at Cannae — but could never take the city.",
     -247, -183, 75, 88),
    (151, "Vlad the Impaler", "Vlad the Impaler", "monarch", "Voivode of Wallachia",
     "Impaled his way into Ottoman nightmares — and, centuries later, into Bram Stoker's Dracula.",
     1431, 1476, 40, None),
    (152, "Scipio Africanus", "Scipio Africanus", "general", "Roman general",
     "The man who finally beat Hannibal, at Zama in 202 BCE.",
     -236, -183, 70, None),
    (153, "Hamilcar", "Hamilcar Barca", "general", "Carthaginian general",
     "Held Sicily in the First Punic War and bound his son Hannibal to eternal enmity with Rome.",
     -275, -228, 60, None),
    (154, "Abraham", "Abraham", "prophet", "Patriarch of three faiths",
     "Father of Isaac and Ishmael — claimed as patriarch by Judaism, Christianity and Islam alike.",
     -1813, -1638, 75, None),
    (155, "Vitalik Buterin", "Vitalik Buterin", "tech", "Ethereum creator",
     "Proposed Ethereum at 19, putting programmable contracts on a blockchain.",
     1994, None, 55, 92),
    (156, "Suleiman the Magnificent", "Suleiman the Magnificent", "emperor", "Ottoman sultan",
     "The Lawgiver, who took the empire to the gates of Vienna and its golden age.",
     1494, 1566, 88, None),
    (157, "Ataturk", "Mustafa Kemal Atatürk", "leader", "Founder of modern Turkey",
     "Victor of Gallipoli who built a secular republic from the Ottoman collapse.",
     1881, 1938, 70, 80),
    (158, "Michael Jackson", "Michael Jackson", "musician", "King of Pop",
     "Thriller remains the best-selling album ever; he redefined performance itself.",
     1958, 2009, 50, None),
    (159, "Elvis Presley", "Elvis Presley", "musician", "King of Rock and Roll",
     "Brought rock and roll from Memphis to the world stage.",
     1935, 1977, 48, None),
    (160, "John Lennon", "John Lennon", "musician", "Beatle",
     "Co-wrote the Beatles songbook with McCartney; shot dead in New York in 1980.",
     1940, 1980, 48, None),
    (161, "Freddie Mercury", "Freddie Mercury", "musician", "Queen frontman",
     "Four-octave showman behind Bohemian Rhapsody and Live Aid's greatest set.",
     1946, 1991, 45, None),
    (162, "Berlusconi", "Silvio Berlusconi", "politician", "Italian media mogul-PM",
     "Media billionaire and four-time prime minister, trailed by scandal throughout.",
     1936, 2023, 55, None),
    (163, "Mozart", "Wolfgang Amadeus Mozart", "composer", "Classical prodigy",
     "More than 600 works by age 35 — operas, symphonies and concertos of effortless perfection.",
     1756, 1791, None, 95),
    (164, "Ramesses II", "Ramesses II", "pharaoh", "Ramesses the Great",
     "A 66-year reign — Abu Simbel, Kadesh, and the first recorded peace treaty.",
     -1303, -1213, 75, None),
    (165, "Nefertiti", "Nefertiti", "pharaoh", "Egyptian queen",
     "Akhenaten's great royal wife at the heart of the Amarna revolution; her Berlin bust is iconic.",
     -1370, -1330, 48, None),
    (166, "Tutankhamun", "Tutankhamun", "pharaoh", "Boy pharaoh",
     "Restored the old gods and died at about 19; his untouched tomb stunned the world in 1922.",
     -1341, -1323, 50, None),
    (167, "Clovis I", "Clovis I", "monarch", "King of the Franks",
     "United the Franks and took Catholic baptism — the founding act of France.",
     466, 511, 60, None),
    (168, "Elon Musk", "Elon Musk", "tech", "Tesla & SpaceX chief",
     "Electric cars, reusable rockets, and the platform formerly known as Twitter.",
     1971, None, 75, 85),
    (169, "Atahualpa", "Atahualpa", "emperor", "Last Inca emperor",
     "Won the Inca civil war just in time to be captured and executed by Pizarro.",
     1502, 1533, 65, None),
    (170, "Nikola Tesla", "Nikola Tesla", "inventor", "Electrical visionary",
     "Alternating current, the induction motor and radio patents — the grid runs on his ideas.",
     1856, 1943, None, 96),
    (171, "Abraham Lincoln", "Abraham Lincoln", "leader", "16th U.S. president",
     "Held the Union together, freed the enslaved, and was murdered five days after victory.",
     1809, 1865, 85, 85),
    (172, "Marie Curie", "Marie Curie", "scientist", "Radioactivity pioneer",
     "First person to win two Nobel Prizes — physics and chemistry; she coined \"radioactivity.\"",
     1867, 1934, None, 96),
    (173, "Kim Jung Il", "Kim Jong Il", "dictator", "North Korean leader",
     "Ruled the DPRK from 1994 to 2011, through famine, while building the bomb.",
     1941, 2011, 45, None),
    (174, "Kim Il Sung", "Kim Il Sung", "dictator", "DPRK founder",
     "Founded North Korea, launched the Korean War, and rules still as \"Eternal President.\"",
     1912, 1994, 50, None),
    (175, "Shaka Zulu", "Shaka", "monarch", "Zulu king",
     "Military innovator who forged the Zulu kingdom with the short spear and the bull-horn formation.",
     1787, 1828, 60, None),
    (176, "Muhammad Ali", "Muhammad Ali", "athlete", "Boxing's Greatest",
     "Three-time heavyweight champion who sacrificed his title to refuse the Vietnam draft.",
     1942, 2016, 45, 65),
    (177, "Konrad Adenauer", "Konrad Adenauer", "leader", "First West German chancellor",
     "Anchored a defeated Germany into the democratic West.",
     1876, 1967, 65, None),
    (178, "Alfred The Great", "Alfred the Great", "monarch", "King of Wessex",
     "Beat back the Vikings and laid the foundations of an English kingdom — and English prose.",
     849, 899, 55, None),
    (179, "Black Beard", "Blackbeard", "criminal", "Pirate",
     "Edward Teach, who tied lit fuses into his beard and blockaded Charleston before losing his head in 1718.",
     1680, 1718, 35, None),
    (180, "Al Capone", "Al Capone", "criminal", "Chicago crime boss",
     "Ran Prohibition Chicago until the taxman got him; Alcatraz finished the job.",
     1899, 1947, 35, None),
    (181, "Pablo Escobar", "Pablo Escobar", "criminal", "Medellín cartel boss",
     "Cocaine made him one of the richest men alive; shot on a Medellín rooftop in 1993.",
     1949, 1993, 38, None),
    (182, "Caligula", "Caligula", "emperor", "Roman emperor",
     "Four years of escalating cruelty and spectacle, ended by his own guards' blades.",
     12, 41, 75, None),
    (183, "Chamberlain", "Neville Chamberlain", "politician", "British prime minister",
     "Brought back \"peace for our time\" from Munich in 1938; war came within a year.",
     1869, 1940, 70, None),
    (184, "Charles I", "Charles I of England", "monarch", "Beheaded English king",
     "His war with Parliament ended on the scaffold in 1649 — the only English king ever executed.",
     1600, 1649, 60, None),
    (185, "Charles II", "Charles II of England", "monarch", "The Merry Monarch",
     "Restored to the throne in 1660 after Cromwell; patron of the Royal Society.",
     1630, 1685, 60, None),
    (186, "Claudius", "Claudius", "emperor", "Roman emperor",
     "The stammering \"fool\" who survived Caligula, conquered Britain, and governed well.",
     -10, 54, 80, None),
    (187, "Da Vinci", "Leonardo da Vinci", "artist", "Renaissance polymath",
     "Mona Lisa, The Last Supper, and notebooks centuries ahead of their time — art and science in one hand.",
     1452, 1519, 40, 100),
    (188, "Margaret Thatcher", "Margaret Thatcher", "leader", "The Iron Lady",
     "Britain's first female prime minister — she privatised, deregulated and divided.",
     1925, 2013, 78, None),
    (189, "Charles Dickens", "Charles Dickens", "writer", "Victorian novelist",
     "Oliver Twist to A Christmas Carol — the conscience of industrial England.",
     1812, 1870, None, 86),
    (190, "Erasmus", "Erasmus", "philosopher", "Prince of the humanists",
     "In Praise of Folly and his Greek New Testament prepared the ground that Luther broke.",
     1466, 1536, None, 90),
    (191, "Freud", "Sigmund Freud", "physician", "Father of psychoanalysis",
     "Vienna's doctor of the unconscious — and the deck's second Freud: the 2018 contract listed him twice.",
     1856, 1939, 40, 92),
    (192, "Gandhi", "Mahatma Gandhi", "activist", "Father of Indian independence",
     "Satyagraha — nonviolent resistance — brought down an empire and inspired movements worldwide.",
     1869, 1948, 70, 85),
    (193, "Che Guevara", "Che Guevara", "revolutionary", "Marxist guerrilla",
     "Argentine doctor who fought in Cuba's revolution and died trying to export it to Bolivia.",
     1928, 1967, 45, None),
    (194, "Stephen Hawking", "Stephen Hawking", "scientist", "Theoretical physicist",
     "Hawking radiation and A Brief History of Time, achieved against near-total paralysis.",
     1942, 2018, None, 96),
    (195, "Henry IV", "Henry IV of France", "monarch", "First Bourbon king of France",
     "\"Paris is worth a Mass\" — converted, then ended the Wars of Religion with the Edict of Nantes.",
     1553, 1610, 65, None),
    (196, "Hindenburg", "Paul von Hindenburg", "general", "Field marshal president",
     "Tannenberg's victor; as president of Germany he handed the chancellorship to Hitler.",
     1847, 1934, 65, None),
    (197, "Ho Chi Min", "Ho Chi Minh", "revolutionary", "Vietnamese revolutionary",
     "Declared Vietnam independent in 1945 and outlasted both France and the United States.",
     1890, 1969, 55, None),
    (198, "Emperor Hirohito", "Hirohito", "monarch", "Shōwa emperor",
     "Reigned through Japan's militarist catastrophe and its astonishing postwar rebirth.",
     1901, 1989, 85, None),
    (199, "Imhotep", "Imhotep", "physician", "Egyptian polymath",
     "Architect of the Step Pyramid at Saqqara; later deified as a god of medicine.",
     -2650, -2600, 40, 85),
    (200, "Ali Jinnah", "Muhammad Ali Jinnah", "leader", "Founder of Pakistan",
     "The Quaid-e-Azam, whose two-nation demand created Pakistan in 1947.",
     1876, 1948, 60, None),
    (201, "Khufu", "Khufu", "pharaoh", "Great Pyramid builder",
     "Fourth-dynasty king whose tomb at Giza stayed the tallest structure on Earth for 3,800 years.",
     -2620, -2566, 58, None),
    (202, "Martin Luther King", "Martin Luther King Jr.", "activist", "Civil-rights leader",
     "\"I Have a Dream\" — led the movement that ended legal segregation; Nobel Peace laureate at 35.",
     1929, 1968, 55, 82),
    (203, "Louis XIV", "Louis XIV", "monarch", "The Sun King",
     "Seventy-two years on the French throne — Versailles, absolutism, \"L'État, c'est moi.\"",
     1638, 1715, 84, None),
    (204, "Jean Moulin", "Jean Moulin", "activist", "French Resistance hero",
     "Unified the Resistance under de Gaulle; died under Gestapo torture without talking.",
     1899, 1943, 30, None),
    (205, "Nehru", "Jawaharlal Nehru", "leader", "First Indian prime minister",
     "Gandhi's political heir, who steered the world's largest democracy through its first 17 years.",
     1889, 1964, 70, None),
    (206, "Nicholas II", "Nicholas II of Russia", "monarch", "Last tsar",
     "His reign ended in revolution; the Bolsheviks shot him with his family at Yekaterinburg.",
     1868, 1918, 82, None),
    (207, "Alfred Nobel", "Alfred Nobel", "inventor", "Dynamite inventor",
     "Made a fortune in explosives and left it to fund the prizes that bear his name.",
     1833, 1896, None, 85),
    (208, "Philippe Petain", "Philippe Pétain", "general", "Vichy chief",
     "Verdun's hero of 1916 became the collaborator of 1940; sentenced to death, he died in prison.",
     1856, 1951, 50, None),
    (209, "Picasso", "Pablo Picasso", "artist", "Modern art's titan",
     "Co-invented Cubism and painted Guernica; twentieth-century art bends around him.",
     1881, 1973, None, 88),
    (210, "Marco Polo", "Marco Polo", "explorer", "Venetian traveller",
     "His account of 24 years on the Silk Road and at Kublai's court fired Europe's imagination.",
     1254, 1324, 55, None),
    (211, "Pythagoras", "Pythagoras", "mathematician", "Greek mathematician-mystic",
     "The theorem, the music of the spheres, and a brotherhood that mixed mathematics with religion.",
     -570, -495, None, 90),
    (212, "Ramesses the Great", "Ramesses II", "pharaoh", "Ramesses the Great",
     "The deck honours Egypt's longest-reigning great pharaoh twice — fitting, for a king who built more monuments to himself than any other.",
     -1303, -1213, 75, None),
    (213, "Ronald Reagan", "Ronald Reagan", "leader", "40th U.S. president",
     "Hollywood actor turned Cold Warrior — \"Tear down this wall.\"",
     1911, 2004, 90, None),
    (214, "Jack the Ripper", "Jack the Ripper", "mystery", "Unidentified killer",
     "Murdered at least five women in 1888 Whitechapel and was never caught — the case that invented the modern manhunt.",
     1855, 1910, 30, 60),
    (215, "Robespierre", "Maximilien Robespierre", "revolutionary", "Architect of the Terror",
     "The Incorruptible sent thousands to the guillotine — then followed them in Thermidor.",
     1758, 1794, 55, 80),
    (216, "Franklin D Roosevelt", "Franklin D. Roosevelt", "leader", "32nd U.S. president",
     "Four terms: the New Deal against the Depression, and victory in sight against the Axis.",
     1882, 1945, 92, None),
    (217, "Theodore Roosevelt", "Theodore Roosevelt", "leader", "26th U.S. president",
     "Trust-buster and Rough Rider — national parks and the Panama Canal.",
     1858, 1919, 85, None),
    (218, "Enver Pasha", "Enver Pasha", "general", "Young Turk leader",
     "Led the Ottomans into World War I; a chief architect of the Armenian genocide.",
     1881, 1922, 55, None),
    (219, "Snofru", "Sneferu", "pharaoh", "Pyramid pioneer",
     "Built three pyramids — including the Bent Pyramid — perfecting the true pyramid for his son Khufu.",
     -2649, -2611, 56, None),
    (220, "Yahya Khan", "Yahya Khan", "general", "Pakistani general-president",
     "His crackdown in East Pakistan ended in the 1971 war and the birth of Bangladesh.",
     1917, 1980, 45, None),
    (221, "Tiberius", "Tiberius", "emperor", "Second Roman emperor",
     "Able soldier and reluctant emperor, remembered for treason trials and the rumours of Capri.",
     -42, 37, 80, None),
    (222, "Titus", "Titus", "emperor", "Roman emperor",
     "Sacked Jerusalem, finished the Colosseum, and handled Vesuvius — then died after just two years.",
     39, 81, 78, None),
    (223, "Trotsky", "Leon Trotsky", "revolutionary", "Red Army founder",
     "Organised the October insurrection and the Red Army; exiled by Stalin, murdered with an ice axe in Mexico.",
     1879, 1940, 55, 88),
    (224, "Turing", "Alan Turing", "mathematician", "Father of computing",
     "Broke Enigma at Bletchley and defined the very idea of the computer; persecuted for being gay.",
     1912, 1954, None, 98),
    (225, "Van Gogh", "Vincent van Gogh", "artist", "Post-Impressionist",
     "Sold barely a painting in his lifetime; The Starry Night and 2,000 works in one decade of fire.",
     1853, 1890, None, 82),
    (226, "Vespasian", "Vespasian", "emperor", "Roman emperor",
     "Won the Year of the Four Emperors, founded the Flavian line, and began the Colosseum.",
     9, 79, 80, None),
    (227, "Victoria", "Queen Victoria", "monarch", "British empress",
     "Her 63-year reign named an age; the empire grew to cover a quarter of the Earth.",
     1819, 1901, 96, None),
    (228, "William Wallace", "William Wallace", "general", "Scottish rebel",
     "Won Stirling Bridge, lost Falkirk, and was executed in London — Scotland's martyr.",
     1270, 1305, 38, None),
    (229, "William II", "Wilhelm II, German Emperor", "monarch", "Last German Kaiser",
     "His bluster helped tip Europe into World War I; abdicated in 1918 and died in exile.",
     1859, 1941, 80, None),
    (230, "Jack Ma", "Jack Ma", "business", "Alibaba founder",
     "English teacher who built China's e-commerce giant — then went quiet after crossing the regulators.",
     1964, None, 65, None),
    (231, "Warren Buffet", "Warren Buffett", "business", "Oracle of Omaha",
     "Turned a failing textile mill into Berkshire Hathaway, history's great compounding machine.",
     1930, None, 60, 90),
    (232, "Stephen King", "Stephen King", "writer", "Master of horror",
     "Carrie, The Shining, It — more than 60 novels and some 350 million copies sold.",
     1947, None, None, 80),
    (233, "Edgar Allan Poe", "Edgar Allan Poe", "writer", "Gothic pioneer",
     "The Raven, the detective story, and the modern horror tale — dead at 40, in mystery.",
     1809, 1849, None, 86),
    (234, "Tolkien", "J. R. R. Tolkien", "writer", "Father of modern fantasy",
     "Oxford philologist whose Middle-earth defined an entire genre.",
     1892, 1973, None, 88),
    (235, "Ram Nath Kovind", "Ram Nath Kovind", "politician", "Indian president",
     "Fourteenth president of India (2017–22), the second from a Dalit background.",
     1945, None, 45, None),
    (236, "Sarkozy", "Nicolas Sarkozy", "politician", "French president",
     "Hyperactive president from 2007 to 2012; later convicted of corruption.",
     1955, None, 60, None),
    (237, "Ben Laden", "Osama bin Laden", "militant", "Al-Qaeda founder",
     "Ordered the September 11 attacks; killed by U.S. Navy SEALs in Abbottabad in 2011.",
     1957, 2011, 50, 65),
    (238, "Ponzi", "Charles Ponzi", "criminal", "The original schemer",
     "His 1920 postal-coupon scam gave every pyramid since his name.",
     1882, 1949, 30, None),
]

# Category base scores: (dominion, intellect).
# Dominion = geographic/political scope of direct power or reach.
# Intellect = weight of intellectual/creative contribution.
CATEGORY_BASES = {
    "founder":       (75, 80),
    "prophet":       (65, 75),
    "religious":     (55, 78),
    "philosopher":   (38, 92),
    "scientist":     (40, 94),
    "mathematician": (36, 95),
    "inventor":      (45, 88),
    "physician":     (40, 88),
    "economist":     (40, 90),
    "conqueror":     (92, 62),
    "emperor":       (84, 60),
    "monarch":       (68, 58),
    "pharaoh":       (62, 55),
    "general":       (70, 65),
    "statesman":     (60, 75),
    "leader":        (78, 65),
    "politician":    (52, 62),
    "dictator":      (74, 55),
    "revolutionary": (58, 68),
    "explorer":      (66, 60),
    "artist":        (35, 78),
    "composer":      (35, 82),
    "writer":        (35, 84),
    "musician":      (40, 58),
    "athlete":       (38, 55),
    "activist":      (48, 72),
    "business":      (60, 80),
    "tech":          (68, 84),
    "criminal":      (35, 60),
    "militant":      (45, 55),
    "mystery":       (45, 75),
}
